batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202304240949
train_epochs: 100
train_workers: 20
vocab: HiZxf&E,e7dogn/FXOr. 4LzK8I3jba0PC6kB)!hT9u;s*"#+QGD?W2Y:lyJMtmq'pN-(vV15cAwRUS
width: 1408
